# name: Fly Deploy
# on:
#   push:
#     branches:
#       - master

# env:
#   FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

# jobs:
#   deploy:
#     name: Deploy app
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: superfly/flyctl-actions/setup-flyctl@master
#       - run: flyctl deploy --remote-only
# Note: There's an issue with this that requires further effort. 
# Use `fly apps restart homebrew-helper` for now.